CREATE DATABASE abdv CHARSET = UTF8 COLLATE = utf8_general_ci;
USE abdv;
CREATE TABLE associados(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
endereco VARCHAR(100) NOT NULL,
telefone VARCHAR(11) NOT NULL,
rg VARCHAR(14) NOT NULL,
cpf VARCHAR(14) NOT NULL,
email VARCHAR(100) NOT NULL,
trabalha VARCHAR(4) NOT NULL,
tipo VARCHAR(30) NOT NULL);
CREATE TABLE login(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL,
senha VARCHAR(20) NOT NULL);

INSERT INTO login(email, senha) VALUES ('marcos.dsv23@gmail.com', 'MAR9252COS8566');