CREATE TABLE associados(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
endereco VARCHAR(100) NOT NULL,
telefone VARCHAR(10) NULL,
celular VARCHAR(11) NULL,
rg VARCHAR(30) NOT NULL UNIQUE,
cpf VARCHAR(11) NOT NULL UNIQUE,
email VARCHAR(100) NULL,
trabalha VARCHAR(4) NOT NULL,
tipo VARCHAR(30) NOT NULL);

CREATE TABLE login(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(100) NOT NULL UNIQUE,
senha VARCHAR(20) NOT NULL);

INSERT INTO login(email, senha) VALUES ('administrador@abdv.org.br', 'administrador@123');
		INSERT INTO login(email, senha) VALUES ('abdv@abdv.org.br', 'abdv@123');